[[news]]
date = "2025-11"
content = "Our work has Won the National award ðŸŽ‰ see https://github.com/brandon-lee-bo/fpgachina2025_47488"

[[news]]
date = "2023-09"
content = "Starting my University life at the South China University of Technology"
